# Generated by Django 5.2.10 on 2026-02-10 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('reg_no', models.CharField(max_length=20)),
                ('gmail', models.EmailField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('student_father_name', models.CharField(max_length=100)),
                ('student_mother_name', models.CharField(max_length=100)),
                ('student_address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UNI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('reg_no', models.CharField(max_length=20)),
                ('course', models.CharField(max_length=100)),
                ('sem', models.IntegerField()),
                ('section', models.CharField(max_length=10)),
            ],
        ),
    ]
